[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
honggfuzz = "0.5.55"
libfuzzer-sys = "0.4"
bincode = { version = "2.0.0-rc.3", tag = "v2.0.0-rc.3", git = "https://github.com/bincode-org/bincode.git" }
cairo-vm = { path = "../vm", features = ["arbitrary"] }
mimalloc = { version = "0.1.29", default-features = false, optional = true }
nom = "7"
thiserror = { version = "1.0.32" }
cairo-felt = { path = "../felt", features = ["arbitrary"] }
proptest = "1.2.0"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.17.0"


[features]
default = ["with_mimalloc"]
with_mimalloc = ["cairo-vm/with_mimalloc", "mimalloc"]

[[bin]]
name = "fuzz_json"
path = "src/fuzz_json.rs"

[[bin]]
name = "cairo_compiled_programs_fuzzer"
path = "src/cairo_compiled_programs_fuzzer.rs"

[[bin]]
name = "fuzz_program"
path = "src/fuzz_program.rs"
